### PR TITLE
Rakefile fixes

### LINKED ISSUE #1750: Ruby: Improve Rakefile smoke_test task
### What

The Rake task `ci:smoke_test` is unused and should be removed from the Rakefile template.

### PR DESCRIPTION
**Pull request by geigerj**
* Remove ci:smoke_test task
* Fix some env variable logic

Updates #1704 (only supports Cloud APIs)
Fixes #1750

### CODE REVIEW

**Comment by geigerj** [comment]
Don't merge until updated to reflect https://github.com/GoogleCloudPlatform/google-cloud-ruby/pull/1920/files.

**Comment by geigerj** [comment]
Updated and ready for review.

File: src/main/java/com/google/api/codegen/transformer/ruby/RubyImportSectionTransformer.java [hunk 1]
```diff
@@ -62,6 +63,21 @@ public ImportSectionView generateTestImportSection(GapicInterfaceContext context
     return importSection.build();
   }
 
+  public ImportSectionView generateRakefileAcceptanceTaskImportSection(
+      List<GapicInterfaceContext> contexts) {
+    List<ImportFileView> none = ImmutableList.of();
+    ImportSectionView.Builder importSection = ImportSectionView.newBuilder();
+    importSection.standardImports(none);
+    importSection.externalImports(none);
+    List<ImportFileView> credentialsImports = new ArrayList<>();
```
Comment (landrito) [inline src/main/java/com/google/api/codegen/transformer/ruby/RubyImportSectionTransformer.java]: This should be a set since multiple interfaces can map to the same credentials class.

Comment (geigerj) [reply src/main/java/com/google/api/codegen/transformer/ruby/RubyImportSectionTransformer.java]: Good catch! Fixed, PTAL.

**Comment by geigerj** [comment]
Sanity check revealed that the credentials imports generated for the `Rakefile` are incorrect and should not contain a version module. Holding off merge to fix.

**Comment by geigerj** [comment]
@landrito Sanity check with container now works. PTAL before I merge?

**Comment by landrito** [comment]
LGTM.
