### PR TITLE
Fix the pattern of param name conflicting with language keywords.

### LINKED ISSUE #618: wrap language keywords for resource name functions
Got a report. With Cloud Functions API (see https://github.com/googleapis/googleapis/blob/master/google/cloud/functions/v1beta2/functions_gapic.yaml#L22), it has `function` variable name.

The generated code looks like:

``` javascript
CloudFunctionsServiceApi.prototype.functionPath = function(project, location, function) {
   ...
```

`function` is a keyword in JS, the third argument needs to be renamed something else (like `function_`).

### PR DESCRIPTION
**Pull request by jmuk**
Fixes #618.

As is seen in the bug, a name pattern for cloud functions
contain 'function' name which becomes to be a parameter of
a function and therefore causes syntax error on JS.

Potentially the same problem could happen in many other languages.
This patch includes fixes on those potential problems.

### CODE REVIEW

File: src/main/java/com/google/api/codegen/util/php/PhpTypeTable.java [hunk 1]
```diff
@@ -105,7 +105,7 @@ public String getAndSaveNicknameForInnerType(
   /**
    * A set of PHP keywords and built-ins. keywords: http://php.net/manual/en/reserved.keywords.php
    */
-  private static final ImmutableSet<String> KEYWORD_BUILT_IN_SET =
+  public static final ImmutableSet<String> KEYWORD_BUILT_IN_SET =
```
Comment (garrettjonesgoogle) [inline src/main/java/com/google/api/codegen/util/php/PhpTypeTable.java]: Could you move all of the `KEYWORD_BUILT_IN_SET` constants to the corresponding `{Lang}NameFormatter` classes? It is a more appropriate location, and I don't think any of them are referenced within the corresponding `{Lang}TypeTable` classes.

File: src/main/java/com/google/api/codegen/util/php/PhpNameFormatter.java [hunk 2]
```diff
@@ -50,22 +58,22 @@ public String varReference(Name name) {
 
   @Override
   public String publicMethodName(Name name) {
-    return name.toLowerCamel();
+    return wrapIfKeywordOrBuiltIn(name.toLowerCamel());
```
Comment (garrettjonesgoogle) [inline src/main/java/com/google/api/codegen/util/php/PhpNameFormatter.java]: Why didn't you do all of the methods in this class?

File: src/main/java/com/google/api/codegen/util/java/JavaNameFormatter.java [hunk 3]
```diff
@@ -50,17 +58,17 @@ public String varReference(Name name) {
```
Comment (garrettjonesgoogle) [inline src/main/java/com/google/api/codegen/util/java/JavaNameFormatter.java]: Handling varReference is necessary too...

File: src/main/java/com/google/api/codegen/util/php/PhpTypeTable.java (hunk 1 above)
Comment (jmuk) [inline src/main/java/com/google/api/codegen/util/php/PhpTypeTable.java]: Done.

**Comment by geigerj** [comment]
Python component LGTM

File: src/main/java/com/google/api/codegen/util/php/PhpNameFormatter.java (hunk 2 above)
Comment (garrettjonesgoogle) [inline src/main/java/com/google/api/codegen/util/php/PhpNameFormatter.java]: @michaelbausor could you answer for PHP?

File: src/main/java/com/google/api/codegen/util/java/JavaNameFormatter.java (hunk 3 above)
Comment (garrettjonesgoogle) [inline src/main/java/com/google/api/codegen/util/java/JavaNameFormatter.java]: Ahh, right.

File: src/main/java/com/google/api/codegen/util/php/PhpNameFormatter.java [hunk 4]
```diff
@@ -17,15 +17,24 @@
...
 import com.google.api.codegen.util.NamePath;
+import com.google.common.collect.ImmutableSet;
 
 /**
  * The NameFormatter for PHP.
  */
 public class PhpNameFormatter implements NameFormatter {
 
+  private String wrapIfKeywordOrBuiltIn(String name) {
+    if (KEYWORD_BUILT_IN_SET.contains(name)) {
```
Comment (garrettjonesgoogle) [inline src/main/java/com/google/api/codegen/util/php/PhpNameFormatter.java]: So PHP is weird in that it treats any casing of a keyword as using that keyword. Examples: `empty`, `Empty`, `EMPTY`. So, you need to do a `toLower()` on the input `name`. Also, there are more functions in this class that need `wrapIfKeywordOrBuiltIn` applied.

File: src/main/java/com/google/api/codegen/util/nodejs/NodeJSNameFormatter.java [hunk 5]
```diff
@@ -17,20 +17,29 @@
...
     return name.toUpperCamel();
   }
 
   @Override
   public String localVarName(Name name) {
-    return name.toLowerCamel();
+    return wrapIfKeywordOrBuiltIn(name.toLowerCamel());
   }
 
   @Override
```
Comment (landrito) [inline src/main/java/com/google/api/codegen/util/nodejs/NodeJSNameFormatter.java]: Why not wrap `*FieldName`s, `*MethodName`s, or `StaticFunctionName`?

File: src/main/java/com/google/api/codegen/util/ruby/RubyNameFormatter.java [hunk 6]
```diff
@@ -17,6 +17,7 @@
 import com.google.api.codegen.util.Name;
 import com.google.api.codegen.util.NameFormatter;
 import com.google.api.codegen.util.NamePath;
+import com.google.common.collect.ImmutableSet;
 
 /**
  * The NameFormatter for Ruby.
```
Comment (landrito) [inline src/main/java/com/google/api/codegen/util/ruby/RubyNameFormatter.java]: Why are we not wrapping here?

File: src/main/java/com/google/api/codegen/util/nodejs/NodeJSNameFormatter.java (hunk 5 above)
Comment (jmuk) [inline src/main/java/com/google/api/codegen/util/nodejs/NodeJSNameFormatter.java]: In NodeJS, the following code is syntactically correct.
```javascript
var foo = {};
foo.function = 'foo';
this.class = 'bar';
foo.prototype.return = function() {};
```

Therefore, field name, method name, etc wouldn't need that.
Static functions might need them.

File: src/main/java/com/google/api/codegen/util/ruby/RubyNameFormatter.java (hunk 6 above)
Comment (jmuk) [inline src/main/java/com/google/api/codegen/util/ruby/RubyNameFormatter.java]: I was just skipping this file. Added (note that skipping private fields intentionally because those are `@foo` style IIRC).

**Comment by jmuk** [comment]
What is the status of the review?
It seems the remaining thing is about PHP and waiting for the review from @michaelbausor ?

**Comment by jmuk** [comment]
ping?

File: src/main/java/com/google/api/codegen/util/php/PhpNameFormatter.java (hunk 2 above)
Comment (michaelbausor) [inline src/main/java/com/google/api/codegen/util/php/PhpNameFormatter.java]: This is correct - variable names and field names do not cause conflicts.

File: src/test/java/com/google/api/codegen/testdata/java_main_library.baseline [hunk 7]
```diff
@@ -233,21 +247,45 @@ public class LibraryServiceApi implements AutoCloseable {
 
   /**
    * Parses the archive_path from the given fully-qualified path which
-   * represents a archivedBook resource.
+   * represents a archived_book resource.
```
Comment (michaelbausor) [inline src/test/java/com/google/api/codegen/testdata/java_main_library.baseline]: Nit: Why is this changing?

Comment (jmuk) [inline src/test/java/com/google/api/codegen/testdata/java_main_library.baseline]: This happens for the consistency with existing path templates -- it's "archived_book" in `formatArchivedBookName` already. Because it's in a comment, it would usually indicate something in "archived_book", not a variable name, so I think this would be okay.

Comment (michaelbausor) [inline src/test/java/com/google/api/codegen/testdata/java_main_library.baseline]: SGTM
