### PR TITLE
Fix doc comments for NodeJS.

### LINKED ISSUE #410: [NodeJS] generate documentation of proto messages
In addition to provide the interface of the generated service APIs (and their methods), we will have to generate the documents of proto messages, like Python/Ruby does.

### PR DESCRIPTION
**Pull request by jmuk**
This patch contains the following updates:
- fix on the parameter types -- now they are Object, with the
  link text to the message definition.
- add NODEJS_DOC generator type and generate message definitions
  in that case.

Fixes #410

### CODE REVIEW

File: src/main/java/com/google/api/codegen/nodejs/NodeJSGapicContext.java [hunk 1]
```diff
@@ -495,4 +578,16 @@ public String getByteLengthFunction(TypeRef typeRef) {
               "options",
               "callback")
           .build();
+
+  private static final ImmutableSet<String> COMMON_PROTO_PATHS =
```
Comment (geigerj) [inline src/main/java/com/google/api/codegen/nodejs/NodeJSGapicContext.java]: It doesn't seem clean to hardcode such information as this and `getFileUrl` into `NodeJSGapicContext`. Will there be a better solution under MVVM?

File: src/main/java/com/google/api/codegen/nodejs/NodeJSGapicContext.java [hunk 2]
```diff
@@ -182,6 +226,21 @@ private String fieldComment(String comment, String paramComment, Field field) {
       paramComment = JSDocCommentFixer.jsdocify(paramComment);
       comment += "\n  " + paramComment.replaceAll("(\\r?\\n)", "\n  ");
     }
+    if (field.getType().isMessage() && !field.getType().isMap()) {
+      if (!Strings.isNullOrEmpty(paramComment)) {
+        comment += "\n";
+      }
+      comment +=
+          "\n  This object should be in the same structure as "
```
Comment (geigerj) [inline src/main/java/com/google/api/codegen/nodejs/NodeJSGapicContext.java]: "be in the same structure" --> "have the same structure"

File: src/main/java/com/google/api/codegen/nodejs/NodeJSGapicContext.java (hunk 1 above)
Comment (geigerj) [inline src/main/java/com/google/api/codegen/nodejs/NodeJSGapicContext.java]: Note: you don't need to address this now.

File: src/main/resources/com/google/api/codegen/nodejs/message.snip [hunk 3]
```diff
@@ -0,0 +1,127 @@
...
+       {@comments(documentation)}
+       *
+     @end
+     {@properties(message)}
+     * @@class
+     * @@see [{@message.getFullName} definition in proto format]{@@link {@context.getFileURL(message.getFile())}}
+     */
+    {@header}
+      // This is for documentation. Actual contents will be loaded by gRPC.
+      @if or(context.filterDocumentingMessages(message), message.getEnums())
```
Comment (geigerj) [inline src/main/resources/com/google/api/codegen/nodejs/message.snip]: Why `or` instead of just two `if` conditions? I think this way will produce extraneous whitespace if one or the other is false.

File: src/main/resources/com/google/api/codegen/nodejs/message.snip [hunk 4]
```diff
@@ -0,0 +1,127 @@
...
+        @let valueDoc = context.defaultComments(value)
+          @if documentation
+            /**
+             {@comments(documentation)}
+             */
+          @end
+          {@value.getSimpleName}: {@value.getNumber}
+        @end
+      @end
+    }
```
Comment (geigerj) [inline src/main/resources/com/google/api/codegen/nodejs/message.snip]: nit: could you add a comment that this closes the curly brace from `{@header}`? Otherwise it is confusing why this is here.

File: src/main/resources/com/google/api/codegen/nodejs/message.snip [hunk 5]
```diff
@@ -0,0 +1,127 @@
...
+       *
+     @end
+     * @@external "{@message.getFullName}"
+     {@properties(message)}
+     * @@see [{@message.getFullName} definition in proto format]{@@link {@context.getFileURL(message.getFile())}}
+     */
+  @end
+@end
+
+@private comments(lines)
```
Comment (geigerj) [inline src/main/resources/com/google/api/codegen/nodejs/message.snip]: optional: Factor this out into a `common.snip` since it also appears in `main.snip`

File: src/main/java/com/google/api/codegen/nodejs/NodeJSGapicContext.java (hunk 2 above)
Comment (jmuk) [inline src/main/java/com/google/api/codegen/nodejs/NodeJSGapicContext.java]: Done

File: src/main/resources/com/google/api/codegen/nodejs/message.snip (hunk 3 above)
Comment (jmuk) [inline src/main/resources/com/google/api/codegen/nodejs/message.snip]: You're right, removed.

File: src/main/resources/com/google/api/codegen/nodejs/message.snip (hunk 4 above)
Comment (jmuk) [inline src/main/resources/com/google/api/codegen/nodejs/message.snip]: Added a comment.

File: src/main/resources/com/google/api/codegen/nodejs/message.snip (hunk 5 above)
Comment (jmuk) [inline src/main/resources/com/google/api/codegen/nodejs/message.snip]: Done

File: src/main/java/com/google/api/codegen/nodejs/NodeJSGapicContext.java (hunk 1 above)
Comment (jmuk) [inline src/main/java/com/google/api/codegen/nodejs/NodeJSGapicContext.java]: I do not have the answer to your question at this point. Let me investigate, but I'm afraid that MVVM will not be that great -- I mean, I suspect that this type of thing will be more specific to Node so either way logic like this would exist in somewhere specific to Node.

**Comment by geigerj** [comment]
LGTM if build passes

Note: I reviewed only Java code and the templates, not the actual JS output -- presumably if needed it can be refined in a later PR.
