### PR TITLE
C# Fix smoketest regression

### LINKED ISSUE #1807: Smoke test regression in C#
The generated smoke tests now have two issues:

- If it's a paginated call, it expects the native response type instead of `PagedEnumerable<...>`. This used to work.
- If it's a long-running operation call, it expects a response type of `Operation` rather than `Operation<...>`, and just prints that response rather than waiting for the operation to complete. This may never have worked.

### PR DESCRIPTION
**Pull request by chrisdunelm**
Fixes #1807

### CODE REVIEW

File: src/main/java/com/google/api/codegen/transformer/csharp/CSharpGapicSmokeTestTransformer.java [hunk 1]
```diff
@@ -145,8 +149,13 @@ private SmokeTestClassView generateSmokeTestCsproj(GapicInterfaceContext context
   }
 
   private StaticLangApiMethodView createSmokeTestCaseApiMethodView(MethodContext methodContext) {
-    StaticLangApiMethodView initialApiMethodView =
-        new CSharpApiMethodTransformer().generateFlattenedMethod(methodContext);
+    MethodConfig methodConfig = methodContext.getMethodConfig();
+    StaticLangApiMethodView initialApiMethodView;
+    if (methodConfig.isPageStreaming()) {
```
Comment (jskeet) [inline src/main/java/com/google/api/codegen/transformer/csharp/CSharpGapicSmokeTestTransformer.java]: Conditional operator?

**Comment by chrisdunelm** [comment]
Yes, this just fixes methods that return lists. A further PR will add support for operations.

File: src/main/java/com/google/api/codegen/transformer/csharp/CSharpGapicSmokeTestTransformer.java (hunk 1 above)
Comment (chrisdunelm) [reply src/main/java/com/google/api/codegen/transformer/csharp/CSharpGapicSmokeTestTransformer.java]: Further `if`s will be required for support of things like operation-based results.
So I'd rather leave it as it is.
